### ISSUE TITLE
[SUGESTÃO] sugiro que "default" seja um endereço local, no caso seria "localhost"

### ISSUE THREAD

**Issue by Paulo-Lopes-Estevao** [pixelinfinito/akeneo-node-n8n#1]
Deixar ele dinamico ficaria melhor no caso em uma variavel de ambiente `.env`

https://github.com/pixelinfinito/akeneo-node-n8n/blob/9e4481234d327ede4291a79e18379bac6ef8cdce/credentials/AkeneoApi.credentials.ts#L41

**Comment by edsonpixel** [comment]
Fica melhor mesmo em uma variável de ambiente.
